# Generated by Django 4.2.8 on 2026-03-11 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="location",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="phone",
        ),
    ]
