# Generated by Django 4.2.8 on 2026-03-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_shop_location_remove_shop_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="shop",
            name="phone",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
