# Generated by Django 4.2.8 on 2026-03-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_shop_location_shop_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="warranty_mileage_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
