# Generated by Django 4.2.8 on 2026-03-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_shop_warranty_mileage_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="qritem",
            name="sold_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
