# Generated by Django 4.2.8 on 2026-03-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_add_sold_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="qritem",
            name="debt_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warehouserecord",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("warranty_check", "Warranty check"),
                    ("reverted", "Reverted"),
                ],
                max_length=32,
            ),
        ),
    ]
