# Generated by Django 4.2.8 on 2026-03-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_add_debt_amount_to_qritem"),
    ]

    operations = [
        migrations.AddField(
            model_name="qritem",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="qritem",
            name="item_type",
            field=models.CharField(
                choices=[("warranty", "Kafolat"), ("repair", "Ta'mirlash")],
                default="warranty",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="qritem",
            name="repair_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="qritem",
            name="repair_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="warehouserecord",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("warranty_check", "Warranty check"),
                    ("reverted", "Reverted"),
                    ("completed", "Completed"),
                ],
                max_length=32,
            ),
        ),
    ]
