# Generated by Django 4.2.8 on 2026-03-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_qritem_repair_ready_to_finish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouserecord",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("warranty_check", "Warranty check"),
                    ("reverted", "Reverted"),
                    ("completed", "Completed"),
                    ("warehouse_ready", "Warehouse ready"),
                ],
                max_length=32,
            ),
        ),
    ]
